SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for crm_temp_module_39
-- ----------------------------
DROP TABLE IF EXISTS `crm_temp_module_39`;
CREATE TABLE `crm_temp_module_39`  (
  `id` int(0) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '1',
  `CUSTOMER_NAME` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '2',
  `CUSTOMER_NAME_KANA` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '3',
  `COMPANY_NAME` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '4',
  `COMPANY_NAME_KANA`TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '5',
  `IDENTIFICATION` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '6',
  `CUSTOMER_CLASS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '7',
  `CUSTOMER_CLASS_NAME` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '8',
  `CUSTOMER_SEX` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '9',
  `CUSTOMER_SEX_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '10',
  `CUSTOMER_GENERATION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '11',
  `CUSTOMER_GENERATION_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '12',
  `HOME_POST_CD` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '13',
  `HOME_FUKEN` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '14',
  `HOME_ADDRESS_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '15',
  `HOME_ADDRESS_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '16',
  `HOME_ADDRESS_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '17',
  `HOME_FAX` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '18',
  `ANY_POST_CD` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '19',
  `ANY_FAX` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '20',
  `EMAIL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '21',
  `NOTE` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '22',
  `BLACKLIST` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '23',
  `BLACKLIST_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '24',
  `RECEIVE_NUMBER` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '25',
  `CAN_BE_TURN_BACK` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '26',
  `RECEIVE_CLASSIFICATION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '27',
  `RECEIVE_CLASSIFICATION_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '28',
  `CONTACT_NUMB_1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '29',
  `CAN_BE_TURN_BACK_1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '30',
  `CONTACT_1_CLASSIFICATION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '31',
  `CONTACT_1_CLASSIFICATION_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '32',
  `CONTACT_NUMB_2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '33',
  `CAN_BE_TURN_BACK_2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '34',
  `CONTACT_2_CLASSIFICATION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '35',
  `CONTACT_2_CLASSIFICATION_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '36',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_cus_id`(`CUSTOMER_ID`) USING BTREE,
  INDEX `idx_cus_class`(`CUSTOMER_CLASS`) USING BTREE,
  INDEX `idx_cus_age`(`CUSTOMER_GENERATION`) USING BTREE,
  INDEX `idx_cus_tel_class`(`RECEIVE_CLASSIFICATION`) USING BTREE,
  INDEX `idx_cus_contact1_class`(`CONTACT_1_CLASSIFICATION`) USING BTREE,
  INDEX `idx_cus_contact2_class`(`CONTACT_2_CLASSIFICATION`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;