SET sql_mode='';

-- update issue_area_correspond_md_1123
UPDATE crm_issue_area_correspond_md_1123 AS corr_md_1123
INNER JOIN crm_temp_issue_survey_detail AS survey_detail_temp ON corr_md_1123.issue_code = survey_detail_temp.CASE_ID
SET 
corr_md_1123.issue_area_correspond_md_1123_cf_1126_multil_lv2_code = survey_detail_temp.SURV_REQ_DESTINATION_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1126_multil_lv2_name = survey_detail_temp.SURV_REQ_DESTINATION_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1160_dept_code = survey_detail_temp.SURV_RESPONDENT_DEPT_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1160_dept_name = survey_detail_temp.SURV_RESPONDENT_DEPT_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1160_person_code = survey_detail_temp.SURV_RESPONDENT_USER_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1160_person_name = survey_detail_temp.SURV_RESPONDENT_USER_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1128_dept_code = survey_detail_temp.SURV_REQ_1_DEPT_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1128_dept_name = survey_detail_temp.SURV_REQ_1_DEPT_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1128_person_code = survey_detail_temp.SURV_REQ_1_USER_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1128_person_name = survey_detail_temp.SURV_REQ_1_USER_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1127 = survey_detail_temp.SURV_REQ_1_CONTENT,
corr_md_1123.issue_area_correspond_md_1123_cf_1127_search = search_field ( survey_detail_temp.SURV_REQ_1_CONTENT ),
corr_md_1123.issue_area_correspond_md_1123_cf_1155_dept_code = survey_detail_temp.SURV_REQ_2_DEPT_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1155_dept_name = survey_detail_temp.SURV_REQ_2_DEPT_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1155_person_code = survey_detail_temp.SURV_REQ_2_USER_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1155_person_name = survey_detail_temp.SURV_REQ_2_USER_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1154 = survey_detail_temp.SURV_REQ_2_CONTENT,
corr_md_1123.issue_area_correspond_md_1123_cf_1154_search = search_field ( survey_detail_temp.SURV_REQ_2_CONTENT ),
corr_md_1123.issue_area_correspond_md_1123_cf_1157_dept_code = survey_detail_temp.SURV_REQ_3_DEPT_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1157_dept_name = survey_detail_temp.SURV_REQ_3_DEPT_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1157_person_code = survey_detail_temp.SURV_REQ_3_USER_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1157_person_name = survey_detail_temp.SURV_REQ_3_USER_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1156 = survey_detail_temp.SURV_REQ_3_CONTENT,
corr_md_1123.issue_area_correspond_md_1123_cf_1156_search = search_field ( survey_detail_temp.SURV_REQ_3_CONTENT ),
corr_md_1123.issue_area_correspond_md_1123_cf_1125_date = DATE_FORMAT( survey_detail_temp.INVST_PROD_SHIPPING_DATE_TIME, '%Y-%m-%d' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1125_time = DATE_FORMAT( survey_detail_temp.INVST_PROD_SHIPPING_DATE_TIME, '%H:%i' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1125_datetime = DATE_FORMAT( survey_detail_temp.INVST_PROD_SHIPPING_DATE_TIME, '%Y-%m-%d %H:%i:%s' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1125_dept_code = survey_detail_temp.INVST_PROD_SHIPPING_DEPT_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1125_dept_name = survey_detail_temp.INVST_PROD_SHIPPING_DEPT_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1125_person_code = survey_detail_temp.INVST_PROD_SHIPPING_USER_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1125_person_name = survey_detail_temp.INVST_PROD_SHIPPING_USER_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1161 = survey_detail_temp.SURV_CONTENT_RESULT_1,
corr_md_1123.issue_area_correspond_md_1123_cf_1161_search = search_field ( survey_detail_temp.SURV_CONTENT_RESULT_1 ),
corr_md_1123.issue_area_correspond_md_1123_cf_1162 = survey_detail_temp.SURV_CONTENT_RESULT_2,
corr_md_1123.issue_area_correspond_md_1123_cf_1162_search = search_field ( survey_detail_temp.SURV_CONTENT_RESULT_2 ),
corr_md_1123.issue_area_correspond_md_1123_cf_1163 = survey_detail_temp.SURV_CONTENT_RESULT_3,
corr_md_1123.issue_area_correspond_md_1123_cf_1163_search = search_field ( survey_detail_temp.SURV_CONTENT_RESULT_3 ),
corr_md_1123.issue_area_correspond_md_1123_cf_1166_date = DATE_FORMAT( survey_detail_temp.INVST_APPR_DATE_TIME, '%Y-%m-%d' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1166_time = DATE_FORMAT( survey_detail_temp.INVST_APPR_DATE_TIME, '%H:%i' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1166_datetime = DATE_FORMAT( survey_detail_temp.INVST_APPR_DATE_TIME, '%Y-%m-%d %H:%i:%s' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1166_dept_code = survey_detail_temp.INVST_APPR_DEPT_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1166_dept_name = survey_detail_temp.INVST_APPR_DEPT_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1166_person_code = survey_detail_temp.INVST_APPR_USER_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1166_person_name = survey_detail_temp.INVST_APPR_USER_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1181_dept_code = survey_detail_temp.SURV_RESULT_APPR_DESTINATION_DEPT_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1181_dept_name = survey_detail_temp.SURV_RESULT_APPR_DESTINATION_DEPT_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1181_person_code = survey_detail_temp.SURV_RESULT_APPR_DESTINATION_USER_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1181_person_name = survey_detail_temp.SURV_RESULT_APPR_DESTINATION_USER_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1165_date = DATE_FORMAT( survey_detail_temp.INVST_APPR_REQ_DATE_TIME, '%Y-%m-%d' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1165_time = DATE_FORMAT( survey_detail_temp.INVST_APPR_REQ_DATE_TIME, '%H:%i' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1165_datetime = DATE_FORMAT( survey_detail_temp.INVST_APPR_REQ_DATE_TIME, '%Y-%m-%d %H:%i:%s' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1165_dept_code = survey_detail_temp.INVST_APPR_REQ_DEPT_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1165_dept_name = survey_detail_temp.INVST_APPR_REQ_DEPT_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1165_person_code = survey_detail_temp.INVST_APPR_REQ_USER_CODE,
corr_md_1123.issue_area_correspond_md_1123_cf_1165_person_name = survey_detail_temp.INVST_APPR_REQ_USER_NAME,
corr_md_1123.issue_area_correspond_md_1123_cf_1128_date = DATE_FORMAT( survey_detail_temp.SURV_REQ_1_DATETIME, '%Y-%m-%d' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1128_time = DATE_FORMAT( survey_detail_temp.SURV_REQ_1_DATETIME, '%H:%i' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1155_date = DATE_FORMAT( survey_detail_temp.SURV_REQ_2_DATETIME, '%Y-%m-%d' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1155_time = DATE_FORMAT( survey_detail_temp.SURV_REQ_2_DATETIME, '%H:%i' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1157_date = DATE_FORMAT( survey_detail_temp.SURV_REQ_3_DATETIME, '%Y-%m-%d' ),
corr_md_1123.issue_area_correspond_md_1123_cf_1157_time = DATE_FORMAT( survey_detail_temp.SURV_REQ_3_DATETIME, '%H:%i' )
WHERE
	corr_md_1123.issue_code IS NOT NULL;
	
-- insert crm_issue_area_correspond_md_1123
INSERT INTO crm_issue_area_correspond_md_1123 ( 
issue_code,
issue_area_correspond_md_1123_cf_1126_multil_lv2_code,
issue_area_correspond_md_1123_cf_1126_multil_lv2_name,
issue_area_correspond_md_1123_cf_1160_dept_code,
issue_area_correspond_md_1123_cf_1160_dept_name,
issue_area_correspond_md_1123_cf_1160_person_code,
issue_area_correspond_md_1123_cf_1160_person_name,
issue_area_correspond_md_1123_cf_1128_dept_code,
issue_area_correspond_md_1123_cf_1128_dept_name,
issue_area_correspond_md_1123_cf_1128_person_code,
issue_area_correspond_md_1123_cf_1128_person_name,
issue_area_correspond_md_1123_cf_1127,
issue_area_correspond_md_1123_cf_1127_search,
issue_area_correspond_md_1123_cf_1155_dept_code,
issue_area_correspond_md_1123_cf_1155_dept_name,
issue_area_correspond_md_1123_cf_1155_person_code,
issue_area_correspond_md_1123_cf_1155_person_name,
issue_area_correspond_md_1123_cf_1154,
issue_area_correspond_md_1123_cf_1154_search,
issue_area_correspond_md_1123_cf_1157_dept_code,
issue_area_correspond_md_1123_cf_1157_dept_name,
issue_area_correspond_md_1123_cf_1157_person_code,
issue_area_correspond_md_1123_cf_1157_person_name,
issue_area_correspond_md_1123_cf_1156,
issue_area_correspond_md_1123_cf_1156_search,
issue_area_correspond_md_1123_cf_1125_date,
issue_area_correspond_md_1123_cf_1125_time,
issue_area_correspond_md_1123_cf_1125_datetime,
issue_area_correspond_md_1123_cf_1125_dept_code,
issue_area_correspond_md_1123_cf_1125_dept_name,
issue_area_correspond_md_1123_cf_1125_person_code,
issue_area_correspond_md_1123_cf_1125_person_name,
issue_area_correspond_md_1123_cf_1161,
issue_area_correspond_md_1123_cf_1161_search,
issue_area_correspond_md_1123_cf_1162,
issue_area_correspond_md_1123_cf_1162_search,
issue_area_correspond_md_1123_cf_1163,
issue_area_correspond_md_1123_cf_1163_search,
issue_area_correspond_md_1123_cf_1166_date,
issue_area_correspond_md_1123_cf_1166_time,
issue_area_correspond_md_1123_cf_1166_datetime,
issue_area_correspond_md_1123_cf_1166_dept_code,
issue_area_correspond_md_1123_cf_1166_dept_name,
issue_area_correspond_md_1123_cf_1166_person_code,
issue_area_correspond_md_1123_cf_1166_person_name,
issue_area_correspond_md_1123_cf_1181_dept_code,
issue_area_correspond_md_1123_cf_1181_dept_name,
issue_area_correspond_md_1123_cf_1181_person_code,
issue_area_correspond_md_1123_cf_1181_person_name,
issue_area_correspond_md_1123_cf_1165_date,
issue_area_correspond_md_1123_cf_1165_time,
issue_area_correspond_md_1123_cf_1165_datetime,
issue_area_correspond_md_1123_cf_1165_dept_code,
issue_area_correspond_md_1123_cf_1165_dept_name,
issue_area_correspond_md_1123_cf_1165_person_code,
issue_area_correspond_md_1123_cf_1165_person_name,
issue_area_correspond_md_1123_cf_1128_date,
issue_area_correspond_md_1123_cf_1128_time,
issue_area_correspond_md_1123_cf_1155_date,
issue_area_correspond_md_1123_cf_1155_time,
issue_area_correspond_md_1123_cf_1157_date,
issue_area_correspond_md_1123_cf_1157_time
) SELECT
survey_detail_temp.CASE_ID,
survey_detail_temp.SURV_REQ_DESTINATION_CODE,
survey_detail_temp.SURV_REQ_DESTINATION_NAME,
survey_detail_temp.SURV_RESPONDENT_DEPT_CODE,
survey_detail_temp.SURV_RESPONDENT_DEPT_NAME,
survey_detail_temp.SURV_RESPONDENT_USER_CODE,
survey_detail_temp.SURV_RESPONDENT_USER_NAME,
survey_detail_temp.SURV_REQ_1_DEPT_CODE,
survey_detail_temp.SURV_REQ_1_DEPT_NAME,
survey_detail_temp.SURV_REQ_1_USER_CODE,
survey_detail_temp.SURV_REQ_1_USER_NAME,
survey_detail_temp.SURV_REQ_1_CONTENT,
search_field ( survey_detail_temp.SURV_REQ_1_CONTENT ),
survey_detail_temp.SURV_REQ_2_DEPT_CODE,
survey_detail_temp.SURV_REQ_2_DEPT_NAME,
survey_detail_temp.SURV_REQ_2_USER_CODE,
survey_detail_temp.SURV_REQ_2_USER_NAME,
survey_detail_temp.SURV_REQ_2_CONTENT,
search_field ( survey_detail_temp.SURV_REQ_2_CONTENT ),
survey_detail_temp.SURV_REQ_3_DEPT_CODE,
survey_detail_temp.SURV_REQ_3_DEPT_NAME,
survey_detail_temp.SURV_REQ_3_USER_CODE,
survey_detail_temp.SURV_REQ_3_USER_NAME,
survey_detail_temp.SURV_REQ_3_CONTENT,
search_field ( survey_detail_temp.SURV_REQ_3_CONTENT ),
DATE_FORMAT( survey_detail_temp.INVST_PROD_SHIPPING_DATE_TIME, '%Y-%m-%d' ),
DATE_FORMAT( survey_detail_temp.INVST_PROD_SHIPPING_DATE_TIME, '%H:%i' ),
DATE_FORMAT( survey_detail_temp.INVST_PROD_SHIPPING_DATE_TIME, '%Y-%m-%d %H:%i:%s' ),
survey_detail_temp.INVST_PROD_SHIPPING_DEPT_CODE,
survey_detail_temp.INVST_PROD_SHIPPING_DEPT_NAME,
survey_detail_temp.INVST_PROD_SHIPPING_USER_CODE,
survey_detail_temp.INVST_PROD_SHIPPING_USER_NAME,
survey_detail_temp.SURV_CONTENT_RESULT_1,
search_field ( survey_detail_temp.SURV_CONTENT_RESULT_1 ),
survey_detail_temp.SURV_CONTENT_RESULT_2,
search_field ( survey_detail_temp.SURV_CONTENT_RESULT_2 ),
survey_detail_temp.SURV_CONTENT_RESULT_3,
search_field ( survey_detail_temp.SURV_CONTENT_RESULT_3 ),
DATE_FORMAT( survey_detail_temp.INVST_APPR_DATE_TIME, '%Y-%m-%d' ),
DATE_FORMAT( survey_detail_temp.INVST_APPR_DATE_TIME, '%H:%i' ),
DATE_FORMAT( survey_detail_temp.INVST_APPR_DATE_TIME, '%Y-%m-%d %H:%i:%s' ),
survey_detail_temp.INVST_APPR_DEPT_CODE,
survey_detail_temp.INVST_APPR_DEPT_NAME,
survey_detail_temp.INVST_APPR_USER_CODE,
survey_detail_temp.INVST_APPR_USER_NAME,
survey_detail_temp.SURV_RESULT_APPR_DESTINATION_DEPT_CODE,
survey_detail_temp.SURV_RESULT_APPR_DESTINATION_DEPT_NAME,
survey_detail_temp.SURV_RESULT_APPR_DESTINATION_USER_CODE,
survey_detail_temp.SURV_RESULT_APPR_DESTINATION_USER_NAME,
DATE_FORMAT( survey_detail_temp.INVST_APPR_REQ_DATE_TIME, '%Y-%m-%d' ),
DATE_FORMAT( survey_detail_temp.INVST_APPR_REQ_DATE_TIME, '%H:%i' ),
DATE_FORMAT( survey_detail_temp.INVST_APPR_REQ_DATE_TIME, '%Y-%m-%d %H:%i:%s' ),
survey_detail_temp.INVST_APPR_REQ_DEPT_CODE,
survey_detail_temp.INVST_APPR_REQ_DEPT_NAME,
survey_detail_temp.INVST_APPR_REQ_USER_CODE,
survey_detail_temp.INVST_APPR_REQ_USER_NAME,
DATE_FORMAT( survey_detail_temp.SURV_REQ_1_DATETIME, '%Y-%m-%d' ),
DATE_FORMAT( survey_detail_temp.SURV_REQ_1_DATETIME, '%H:%i' ),
DATE_FORMAT( survey_detail_temp.SURV_REQ_2_DATETIME, '%Y-%m-%d' ),
DATE_FORMAT( survey_detail_temp.SURV_REQ_2_DATETIME, '%H:%i' ),
DATE_FORMAT( survey_detail_temp.SURV_REQ_3_DATETIME, '%Y-%m-%d' ),
DATE_FORMAT( survey_detail_temp.SURV_REQ_3_DATETIME, '%H:%i' )
FROM
	crm_temp_issue_survey_detail AS survey_detail_temp
	LEFT JOIN crm_issue_area_correspond_md_1123 AS corr_md_1123 ON survey_detail_temp.CASE_ID = corr_md_1123.issue_code 
WHERE
	corr_md_1123.issue_code IS NULL 
	OR corr_md_1123.issue_code = '';